#!/usr/bin/env python3
"""
Del Norte County analysis orchestrator.

Runs forest health, coastal resilience, and fire risk analyzers using real
data integrators where implemented, and saves outputs in the location's
`del_norte_dashboard/` directory.

Features:
- Cleans up outdated results before running new analysis
- Keeps only the most recent files for each output type
- Comprehensive multi-domain analysis integration
- Real-time API integration with caching

Usage:
  python3 run_analysis.py
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path

from geo_infer_place.locations.del_norte_county.forest_health_monitor import (
    ForestHealthMonitor,
)
from geo_infer_place.locations.del_norte_county.coastal_resilience_analyzer import (
    CoastalResilienceAnalyzer,
)
from geo_infer_place.locations.del_norte_county.fire_risk_assessor import (
    FireRiskAssessor,
)
from geo_infer_place.locations.del_norte_county.seismic_hazard_analyzer import (
    SeismicHazardAnalyzer,
)
from geo_infer_place.locations.del_norte_county.dashboard import (
    AdvancedDashboard,
)
from geo_infer_place.utils.integration import DelNorteDataIntegrator
from geo_infer_place.core.module_bridge import PlaceDataManager, PlaceTemporalAnalyzer


def load_location_config() -> dict:
    config_path = Path(__file__).parent / "config" / "analysis_config.yaml"
    try:
        import yaml

        with open(config_path) as f:
            return yaml.safe_load(f) or {}
    except Exception:
        # Minimal default bounds if YAML not available
        return {
            "location": {
                "bounds": {
                    "north": 42.006,
                    "south": 41.458,
                    "east": -123.536,
                    "west": -124.408,
                }
            },
            "spatial": {"h3_resolution": 8},
            "analyses": {
                "forest_health": {},
                "coastal_resilience": {},
                "fire_risk": {},
            },
        }


def cleanup_old_results(output_dir: Path) -> None:
    """
    Clean up outdated analysis results and dashboards, keeping only the most recent.

    This function removes old files while preserving:
    - The most recent HTML dashboard
    - The most recent combined results JSON
    - The most recent individual analysis JSON files
    - The most recent GeoJSON files

    Args:
        output_dir: Path to the dashboard output directory
    """
    if not output_dir.exists():
        return

    # File patterns to clean up (with timestamp extraction regex)
    patterns = {
        "html_dashboards": (
            re.compile(r"del_norte_intelligence_dashboard_(\d{8}_\d{6})\.html"),
            "html",
        ),
        "combined_results": (
            re.compile(r"del_norte_combined_results_(\d{8}_\d{6})\.json"),
            "json",
        ),
        "forest_health": (
            re.compile(r"forest_health_analysis_(\d{8}_\d{6})\.json"),
            "json",
        ),
        "coastal_resilience": (
            re.compile(r"coastal_resilience_analysis_(\d{8}_\d{6})\.json"),
            "json",
        ),
        "fire_risk": (re.compile(r"fire_risk_analysis_(\d{8}_\d{6})\.json"), "json"),
        "fire_perimeters": (
            re.compile(r"fire_perimeters_(\d{8}_\d{6})\.geojson"),
            "geojson",
        ),
        "seismic_hazard": (
            re.compile(r"seismic_hazard_analysis_(\d{8}_\d{6})\.json"),
            "json",
        ),
    }

    # Files to preserve (not generated by this script)
    preserve_files = set()

    # Group files by pattern and find the most recent for each
    files_to_keep: dict[str, Path | None] = {}
    files_to_remove: list[Path] = []

    for pattern_name, (pattern, _) in patterns.items():
        matching_files = []

        for file_path in output_dir.iterdir():
            if file_path.name in preserve_files:
                continue

            match = pattern.match(file_path.name)
            if match:
                timestamp_str = match.group(1)
                try:
                    # Convert timestamp to datetime for comparison
                    timestamp = datetime.strptime(timestamp_str, "%Y%m%d_%H%M%S")
                    matching_files.append((file_path, timestamp))
                except ValueError:
                    continue  # Skip files with malformed timestamps

        if matching_files:
            # Sort by timestamp (newest first) and keep the most recent
            matching_files.sort(key=lambda x: x[1], reverse=True)
            files_to_keep[pattern_name] = matching_files[0][0]

            # Add older files to removal list
            for file_path, _ in matching_files[1:]:
                files_to_remove.append(file_path)

    # Remove outdated files
    removed_count = 0
    for file_path in files_to_remove:
        try:
            file_path.unlink()
            removed_count += 1
            print(f"🗑️  Removed outdated file: {file_path.name}")
        except Exception as e:
            print(f"⚠️  Failed to remove {file_path.name}: {e}")

    # Report what was kept
    kept_count = len(files_to_keep)
    if kept_count > 0:
        print(f"✅ Kept {kept_count} most recent files:")
        for pattern_name, file_path in files_to_keep.items():
            if file_path:
                print(f"   - {pattern_name}: {file_path.name}")
    else:
        print("ℹ️  No recent files found to keep")

    if removed_count > 0:
        print(f"🧹 Cleanup complete: removed {removed_count} outdated files")
    else:
        print("🧹 Cleanup complete: no outdated files to remove")


def main() -> None:
    base_dir = Path(__file__).parent
    output_dir = base_dir / "del_norte_dashboard"
    output_dir.mkdir(parents=True, exist_ok=True)

    config = load_location_config()

    # Data integrator (real API wrappers)
    integrator = DelNorteDataIntegrator()

    # Data quality and temporal analysis bridges
    data_mgr = PlaceDataManager()
    temporal = PlaceTemporalAnalyzer()

    # Initialize analyzers with shared integrator and write outputs next to dashboard
    forest = ForestHealthMonitor(
        config=config,
        data_integrator=integrator,
        spatial_processor=None,
        output_dir=output_dir,
    )
    coastal = CoastalResilienceAnalyzer(
        config=config,
        data_integrator=integrator,
        spatial_processor=None,
        output_dir=output_dir,
    )
    fire = FireRiskAssessor(
        config=config,
        data_integrator=integrator,
        spatial_processor=None,
        output_dir=output_dir,
    )
    seismic = SeismicHazardAnalyzer(
        config=config,
        data_integrator=integrator,
        spatial_processor=None,
        output_dir=output_dir,
    )

    # Run analyses
    results = {
        "forest_health": forest.run_analysis(),
        "coastal_resilience": coastal.run_analysis(),
        "fire_risk": fire.run_analysis(),
        "seismic_hazard": seismic.run_analysis(),
    }

    # Data quality validation
    for name, data in results.items():
        quality = data_mgr.validate_dataset(data, name=name)
        data_mgr.log_provenance(name, {"quality": quality})
        print(f"  {name}: completeness={quality.get('completeness', 0):.1%}")

    # Temporal analysis on tide data
    try:
        tide_data = integrator.noaa_client.get_tide_gauge_data()
        if tide_data.get("series"):
            results["temporal_tide_trends"] = temporal.analyze_tide_trends(tide_data)

        csz_data = results.get("seismic_hazard", {}).get("cascadia_seismicity", {})
        if csz_data.get("events"):
            results["temporal_seismic_rates"] = temporal.analyze_seismic_rates(csz_data)
    except Exception as e:
        print(f"  Temporal analysis skipped: {e}")

    results["provenance"] = data_mgr.get_provenance()

    # Persist unified results
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    (output_dir / f"del_norte_combined_results_{ts}.json").write_text(
        json.dumps(results, indent=2, default=str)
    )

    # Generate and save interactive dashboard
    dash = AdvancedDashboard(output_dir=str(output_dir))
    html_path = dash.save_dashboard()
    print(html_path)

    # Clean up outdated results after generating new ones, keeping only the most recent
    print("🧹 Cleaning up outdated results...")
    cleanup_old_results(output_dir)


if __name__ == "__main__":
    main()
